name: S2S-DotNetCore10

services:
  rabbitmq:
    image: rabbitmq:4.2.3
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    restart: unless-stopped

  operationalservice:
    image: operational-service:latest
    build:
      context: .
      dockerfile: src/OperationalService/Dockerfile
    container_name: operationalservice
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DatabaseConnectionString: Host=postgres;Port=5432;Database=db;Username=user;Password=pass
      Jaeger__Host: jaeger
      RabbitMQ__Host: rabbitmq
    ports:
      - "5000:8080"

  # workloadservice:
  #   image: workload-service:latest
  #   build:
  #     context: .
  #     dockerfile: src/WorkloadService/Dockerfile
  #   container_name: workloadservice
  #   command: --rabbitmq-host rabbitmq
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
